feat: view userTaskRun notes
littlehorse-enterprises/littlehorse pull request #844
Opened 2024-05-29 20:31 UTC by HazimAr

2024-05-29 20:32 UTC, HazimAr commented
Before: 
<img width="302" alt="image" src="https://github.com/littlehorse-enterprises/littlehorse/assets/64544952/2832c7d3-8d84-435d-a5be-09d7b2e2a6bf">

After:
<img width="241" alt="image" src="https://github.com/littlehorse-enterprises/littlehorse/assets/64544952/2b8b413d-e68a-4940-81a7-4e8e2e37f73b">

2024-05-29 21:00 UTC, coltmcnealy-lh commented
Screenshots look good, well done

2024-05-30 14:13 UTC, mijailr requested changes
Looks like the heroicon removal had broken the image build. Please check if there are still some components using HeroIcons

2024-05-30 15:30 UTC, mijailr approved these changes

2024-05-30 15:31 UTC, merged