Progress on major docs overhaul
littlehorse-enterprises/littlehorse pull request #934
Opened 2024-07-28 18:18 UTC by coltmcnealy-lh

This is in progress. Some highlights:

- Making the `Concepts` section easier to understand and more high-level
- Moving low-level details out of `Concepts` and into the `Developer Guide`
- Adding docs for principals + tenants

2024-07-29 15:59 UTC, Snarr commented on docs/docs/01-overview.md
> +LittleHorse is not an API Management System like Apigee or Kong. Those systems define
Define what 🤔

2024-07-29 16:09 UTC, Snarr commented on docs/docs/04-concepts/30-advanced/10-child-workflows.md
> +A Child Workflow allows you to
A Child Workflow allows you to launch a new WfRun that is tied to a Parent WfRun. This is similar to the concept of Child Process in operating systems, where a Parent Process spawns a Child Process and can pass down information to it at runtime.

Is this a good start to this page? If so I can continue, and if not, let's discuss this concept more.

2024-07-29 16:10 UTC, Snarr commented on docs/docs/04-concepts/30-advanced/05-workflow-lifecycle.md
> +# Workflow Lifecycle
Don't forget about these pages. Maybe we could add an 'UNDER CONSTRUCTION' flag to any page that is in progress.

2024-07-29 16:12 UTC, Snarr requested changes
The docs overhaul looks amazing. I merged some of my own changes and left a few comments about unfinished sections.

2024-08-05 01:39 UTC, coltmcnealy-lh commented
This is ready now

2024-08-05 15:53 UTC, Snarr commented on docs/docusaurus.config.js
> +  // Colt gets very grumpy when links don't work.
Nice

2024-08-05 15:55 UTC, Snarr approved these changes
Looks great 👍 This is a great kickoff to our new docs improvements.

2024-08-05 19:14 UTC, merged